### ISSUE TITLE
Improve the doc

### ISSUE THREAD

**Issue by SylvainTakerkart** [INT-NIT/AnDOChecker#15]
Hi, we should improve the content of the doc that is now visible at https://int-nit.github.io/AnDOChecker/

**Comment by SylvainTakerkart** [comment]
Hi @Slowblitz , I think we should discuss the content of the https://int-nit.github.io/AnDOChecker/ page... This should become the main access point of the users!

So maybe it could include both
- the specs (as it is at the moment)
- and the doc (what's visible here at the moment: https://github.com/INT-NIT/AnDOChecker, i.e how to install it? how to use it? the existence of the CLI; how to setup the web interface; etc. (we probably don't need the videos, which have a low added value compared to just giving an example)

And then, what we see at https://github.com/INT-NIT/AnDOChecker (through the README.md at the root) should just be a one sentence explanation about AnDO and a link to https://int-nit.github.io/AnDOChecker/

What do you think? (before doing it, I think we should agree on what to do more precisely ;) )




the doc in the README.md file at the root of https://github.com/INT-NIT/AnDOChecker should be updated

**Comment by Slowblitz** [comment]
Hi @SylvainTakerkart, yes I see what you want to do but I don't know if it's really useful to include the doc in the "gh-pages",
If we include the doc, i.e. how to install it ? Etc… The user have to go on GitHub download the project then go on another site to see how it's works etc, instead of just staying on the GitHub project page (master) seems a bit boring to me.
And yes  I am agree on updated the README.md file at the root of https://github.com/INT-NIT/AnDOChecker.

**Comment by SylvainTakerkart** [comment]
well, I think the user will never have to go to the github project page, it's only for developers... especially since the installation instruction will only be something like "use pip by typing "pip install AnDOChecker"... no?

so I think the gh-page should become THE webpage for the user...

WDYT?

**Comment by SylvainTakerkart** [comment]
...for example:
@Slowblitz 
for example, with sklearn:
- the user webpage: https://scikit-learn.org
- the github project page for developers: https://github.com/scikit-learn/scikit-learn
(but they have the installation instruction on both... I think it's mostly important to have the installation instruction available for the users on the "user webpage")

**Comment by Slowblitz** [comment]
Seems good to have the installation on both the gh-pages and the read me yes .

**Comment by Slowblitz** [comment]
Also I need to have the access on repo to modify the github pages .

**Comment by SylvainTakerkart** [comment]
> Also I need to have the access on repo to modify the github pages .

it's not configured in the code? can't you do a PR to do this? (I'm ignorant...)

anyhow, I've just added you as a "Maintainer" of the project... tell me if you can do what you need! (if not, I can upgrade you from "Maintainer" to "Admin"... but I just want to test what the "Maintainer" role allows)

**Comment by SylvainTakerkart** [comment]
@Slowblitz I've just updated https://int-nit.github.io/AnDOChecker/
Can you check it out and let me know if you see things that we should change?
Thanks!

**Comment by Slowblitz** [comment]
Hi @SylvainTakerkart, seems good to me.
Just little note I have forgotten to add, Ando only works in "Python3", maybe we should add this at the end, and update the "setup.py"  by adding  "python_requires='>=3.6'"  as describe here https://packaging.python.org/tutorials/packaging-projects/.
WDYT?

**Comment by SylvainTakerkart** [comment]
> Hi @SylvainTakerkart, seems good to me.

ok! So we're good to go for the gh pages!

> Just little note I have forgotten to add, Ando only works in "Python3", maybe we should add this at the end, and update the "setup.py" by adding "python_requires='>=3.6'" as describe here https://packaging.python.org/tutorials/packaging-projects/.
> WDYT?

ok for me!


But also, the main README.md file should be updated, no? So that what's visible on the main page ( https://github.com/INT-NIT/AnDOChecker ) is up to date... Can you do it?

**Comment by Slowblitz** [comment]
Yes I can update the main README.md but can you be more specific on what to update ? 
Do you mean an overall update ? Or just a one sentence explanation about AnDO and a link to https://int-nit.github.io/AnDOChecker/ ?

**Comment by SylvainTakerkart** [comment]
it would be good to have a general update, no? lots of things have changed... i guess we could have a short description (to be copy-pasted from somewhere else), installation instruction (using pip), a short demo of the CLI (just some lines of code... the videos are probably not needed anymore... WDYT?), plus the link to the gh-pages specs...

**Comment by Slowblitz** [comment]
Ok for a general update.Yes videos can probably be deleted at this point.

- [ ] Short description.
- [ ] installation instruction.
- [ ]  CLI  exemples .
- [ ] link to the gh-pages specs.

**Comment by SylvainTakerkart** [comment]
@Slowblitz I think most of the content of this issue has been taken care of! Thanks!

However, there's still something: we still have a "doc" and a "docs" directory at the root of the repository... This is not very good ;) Could you try to re-organize  the content of these two directories and/or rename them so that we get something that is a bit cleaner?

**Comment by Slowblitz** [comment]
Hello,

We just have to remove the "docs" folder we do not need it anymore, do you want a single pull request for that or should I fix it on the current pull request ? #42

**Comment by SylvainTakerkart** [comment]
> Hello,
> 
> We just have to remove the "docs" folder we do not need it anymore, do you want a single pull request for that or should I fix it on the current pull request ? #42

ok, just do it in #42 !
