### ISSUE TITLE
Bug in the checking folder

### ISSUE THREAD

**Issue by BlaizeKevin** [INT-NIT/AnDOChecker#29]
![image](https://user-images.githubusercontent.com/70888029/92396925-28931300-f126-11ea-8142-5d73ed4bc326.png)

As shown in the picture attached, some error are not justified (according to me).

**Comment by Slowblitz** [comment]
Hi I updated the API, it's seems that the feedback was wrong at the session level ,now works for me :
![image](https://user-images.githubusercontent.com/17256769/92397916-e1a61d00-f127-11ea-882a-b436b2e3bf87.png)

**Comment by SylvainTakerkart** [comment]
@Slowblitz has it been pushed to the web server?
