### ISSUE TITLE
Setting up of an abstraction for the rules

### ISSUE THREAD

**Issue by SylvainTakerkart** [INT-NIT/AnDOChecker#34]
As discussed together, let's try to think about how to formalize the rules / design a proper schema... This post points to something that has been done for this in BIDS (if I understood correctly): https://github.com/INCF/neuroscience-data-structure/issues/4#issuecomment-690383638

**Comment by SylvainTakerkart** [comment]
@Slowblitz on this one, you did create a json file, right (I remembered you showed it to me at some point)? but I can't find it in the code... Is it there?

**Comment by Slowblitz** [comment]
Yes I have already, created it, I will add it in the next pull request with all the other task at https://github.com/INT-NIT/AnDOChecker/projects/1
