### ISSUE TITLE
updating specs

### ISSUE THREAD

**Issue by SylvainTakerkart** [INT-NIT/AnDOChecker#35]
Hi!

On the online docs, there are a few things to fix:
- the very first sentence (we can remove or modify "this is the very first draft...")
- the sub-subName (and the other equivalent names at the different levels of the hierarchy) in the figure, which should be sub-GUID (it should be strictly the same as in the specs)
- there should be a link with the github developer's andochecker url
etc.

**Comment by Slowblitz** [comment]
Hi !
I have made some changes as asked above : 

- [ x] the very first sentence (we can remove or modify "this is the very first draft...")

- [ x] the sub-subName (and the other equivalent names at the different levels of the hierarchy) in the figure, which should be sub-GUID (it should be strictly the same as in the specs)

- [x ] there should be a link with the github developer's andochecker url

See https://github.com/INT-NIT/AnDOChecker/blob/gh-pages/README.md for more details.
