### ISSUE TITLE
Spec : Source directory 

### ISSUE THREAD

**Issue by Slowblitz** [INT-NIT/AnDOChecker#36]
Hi ! 
It seems like the Checker ask for a "source" directory but it's not described in the Specs page.

- [x] Deleting Source rules

- [x] Modifying check function verbose 

- [x] Modifying check function non verbose 

- [x] Updating Pypi package 

- [ ] Updating Web server app

Happy fixing =)

**Comment by SylvainTakerkart** [comment]
I think we can close this one! We will be updating the web app when the v0.2 is finalized, tagged and released on pip... OK @Slowblitz ?

**Comment by Slowblitz** [comment]
Seems good to me, I have just added the card in the TODO list at https://github.com/INT-NIT/AnDOChecker/projects/1

**Comment by SylvainTakerkart** [comment]
ok, thanks!
